version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: traffic
    ports:
      - "5432:5432"

  producer:
    build:
      context: ./kafka-producer
    volumes:
      - ./data:/data
    working_dir: /app
    depends_on:
      - kafka
    command: python producer.py

  spark:
    build:
      context: ./spark
    working_dir: /opt/spark
    volumes:
      - ./spark:/opt/spark
      - ./data:/opt/spark/data
      - ./output:/opt/spark/output
    depends_on:
      - kafka
      - postgres
    command: python process_batch.py

  visualizer:
    build:
      context: ./visualizer
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    container_name: visualizer
    command: python process_batch.py

